#
# Project nurikit - Copyright 2023 SNU Compbio Lab.
# SPDX-License-Identifier: Apache-2.0
#
---
# The rules below have been manually copied from @commitlint/config-conventional
# and match the v1.0.0 specification:
# https://www.conventionalcommits.org/en/v1.0.0/#specification
#
# You can remove them and uncomment the config below when the following issue is
# fixed: https://github.com/conventional-changelog/commitlint/issues/613
# EXCEPT the *-length entries, which were modified by us.
#
# extends:
#   - '@commitlint/config-conventional'
rules:
  header-max-length: [2, always, 72]
  body-max-line-length: [2, always, 72]
  footer-max-line-length: [1, always, 100]
  body-leading-blank: [1, always]
  footer-leading-blank: [1, always]
  subject-case:
    - 2
    - never
    - [sentence-case, start-case, pascal-case, upper-case]
  subject-empty: [2, never]
  subject-full-stop: [2, never, "."]
  type-case: [2, always, lower-case]
  type-empty: [2, never]
  type-enum:
    - 2
    - always
    - [build, chore, ci, docs, feat, fix, perf, refactor, revert, style, test]
parserPreset:
  parserOpts:
    noteKeywords:
      - '\[.+\]:'
