#
# Project NuriKit - Copyright 2024 SNU Compbio Lab.
# SPDX-License-Identifier: Apache-2.0
#

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-23.11"
  apt_packages:
    - build-essential
    - ninja-build
    - doxygen
    - graphviz
  jobs:
    post_checkout:
      - (git show -s --format='%an' | grep -vq '\[bot\]$') || exit 183
    pre_install:
      - |
        cmake -S . -B pre-install -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DNURI_ENABLE_IPO=OFF \
          -DNURI_OPTIMIZATION_LEVEL=O0
    post_install:
      - cmake --build pre-install --target clean
    pre_build:
      - |
        cmake -S . -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
          -DNURI_BUILD_DOCS=ON \
          -DNURI_BUILD_PYTHON_DOCS=ON \
          -DNURI_ENABLE_IPO=OFF \
          -DNURI_OPTIMIZATION_LEVEL=O0
      - cmake --build build --target NuriDocs

conda:
  environment: docs/environment.yaml

python:
  install:
    - method: pip
      path: "."
      extra_requirements:
        - docs

sphinx:
  configuration: "python/docs/conf.py"
