#
# Project NuriKit - Copyright 2023 SNU Compbio Lab.
# SPDX-License-Identifier: Apache-2.0
#

name: Upload to pypi

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  publish:
    runs-on: ubuntu-latest

    environment:
      name: release
      url: https://pypi.org/p/nurikit

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          pattern: cibw-wheels-*
          path: dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1

      # https://packaging.python.org/en/latest/specifications/version-specifiers/#public-version-identifiers
      # Check if the version ends with a/b/rc or .dev (could also include post release number)
      - id: prerelease-check
        run: |
          regex='((a|b|rc)([[:digit:]]+\.post)?|\.dev)[[:digit:]]+$'

          if grep -E "$regex" <<<"$GITHUB_REF"; then
            echo prerelease=true >> $GITHUB_OUTPUT
          else
            echo prerelease=false >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_REF: ${{ github.ref }}

      - uses: softprops/action-gh-release@v2
        with:
          files: "dist/*.whl"
          fail_on_unmatched_files: true
          generate_release_notes: true
          prerelease: ${{ steps.prerelease-check.outputs.prerelease == 'true' }}
