#
# Project nurikit - Copyright 2023 SNU Compbio Lab.
# SPDX-License-Identifier: Apache-2.0
#

name: Upload to pypi

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  publish:
    runs-on: ubuntu-latest

    environment:
      name: release
      url: https://pypi.org/p/nurikit

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          name: wheels
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1

      - uses: softprops/action-gh-release@v1
        with:
          files: "dist/*.whl"
          fail_on_unmatched_files: true
          generate_release_notes: true
