#
# Project NuriKit - Copyright 2024 SNU Compbio Lab.
# SPDX-License-Identifier: Apache-2.0
#

name: Label pre-commit CI autoupdates

on:
  pull_request_target:
    types: [opened]
    paths: [.pre-commit-config.yaml]

jobs:
  label:
    if: ${{ github.triggering_actor == 'pre-commit-ci[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v8
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['dependencies', 'pre-commit']
            })
