#
# Project nurikit - Copyright 2023 SNU Compbio Lab.
# SPDX-License-Identifier: Apache-2.0
#

name: Build and deploy docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: [self-hosted, galaxy3]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure with cmake
        run: |
          cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -S . -B build -G Ninja

      - name: Build docs
        run: |
          cmake --build build --target nurikit_docs -j4

      - name: Deploy
        run: |
          output="$HOME/www/html/docs/nurikit/$(git rev-parse --abbrev-ref HEAD)/"
          mkdir -p "$output"
          rsync -avh --delete build/generated/docs/html/ "$output"
