#
# Project nurikit - Copyright 2023 SNU Compbio Lab.
# SPDX-License-Identifier: Apache-2.0
#

name: Build and deploy python docs

on:
  workflow_dispatch:
  workflow_call:
  release:
    types:
      - published

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "py-docs"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: pip install sphinx sphinx-rtd-theme nurikit

      - name: Configure with cmake
        run: |
          cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -S . -B build

      - name: Build docs & test
        run: |
          cmake --build build -j \
            --target nuri_python_docs nuri_python_docs_doctest

      - uses: actions/upload-artifact@v3
        with:
          name: pydocs
          path: build/python/docs/html/**

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/configure-pages@v4
      - uses: actions/download-artifact@v3
        with:
          name: pydocs
          path: _site
      - uses: actions/upload-pages-artifact@v2
      - uses: actions/deploy-pages@v3
        id: deployment
